### ISSUE TITLE
I get this error when clicking load (Ubuntu 16.04)

### ISSUE THREAD

**Issue by CasualPlayer1337** [10se1ucgo/pyjam#11]
An error has occured!

Traceback (most recent call last):
  File "<string>", line 167, in start_stop
  File "jam_tools.py", line 241, in start
  File "jam_tools.py", line 330, in write_configs
FileNotFoundError: [Errno 2] No such file or directory: '/home/brevz/.local/share/Steam/ubuntu12_32/steamapps/common/Counter-Strike Global Offensive/csgo/cfg/jam.cfg'

**Comment by sKuhLight** [comment]
Maybe im late but u have to setup ur csgo folder under file > settings > Game Folder.
In the DropDown click on others and navigate to:
"/home/brevz/.steam/steam/steamapps/common/Counter-Strike Global Offensive/csgo/"
or the folder u installed csgo. 

Save Game, restart pyjam and hopefully its working :D Maybe u have to exec the jam.cfg ingame( i have to)
