### ISSUE TITLE
OSError: Path is not a directory 

### ISSUE THREAD

**Issue by lolmikes** [10se1ucgo/pyjam#9]
**LOG:**

``` python
14:44:44 INFO: Python 3.4.2 (default, Oct  8 2014, 10:47:48) 
[GCC 4.9.1] on linux
14:44:44 INFO: uname_result(system='Linux', node='michael-pc', release='4.4.22-1-MANJARO', version='#1 SMP PREEMPT Sat Sep 24 11:25:42 UTC 2016', machine='x86_64', processor='')
14:44:44 INFO: pyjam version 1.2.9
14:44:44 INFO: Generating track list with path audio/csgo
14:44:49 INFO: Generating track list with path /run/media/michael/General/MusicSpam
14:44:51 INFO: Generating track list with path /run/media/michael/General/MusicSpam
14:44:52 CRITICAL: Traceback (most recent call last):
  File "<string>", line 167, in start_stop
  File "jam_tools.py", line 240, in start
  File "watchdog/observers/api.py", line 255, in start
  File "watchdog/utils/__init__.py", line 111, in start
  File "watchdog/observers/inotify.py", line 121, in on_thread_start
  File "watchdog/observers/inotify_buffer.py", line 35, in __init__
  File "watchdog/observers/inotify_c.py", line 187, in __init__
  File "watchdog/observers/inotify_c.py", line 363, in _add_dir_watch
OSError: Path is not a directory

```

**Comment by lolmikes** [comment]
This happens when I click the "Start" button

**Comment by 10se1ucgo** [comment]
Hi, would you mind attaching a copy of your `config.json`? Thanks.

**Comment by lolmikes** [comment]
I've tried using tf/custom and that didn't work either. Umm. This stuff is to hard for me. I hope you meant the jamconfig.json

``` python
 {
    "games": [
        {
            "audio_dir": "audio/csgo",
            "audio_rate": 22050,
            "mod_path": "/home/michael/.local/share/Steam/ubuntu12_32/steamapps/common/Counter-Strike Global Offensive/csgo",
            "name": "Counter-Strike: Global Offensive",
            "play_key": "F8",
            "relay_key": "=",
            "use_aliases": true
        },
        {
            "audio_dir": "audio/css",
            "audio_rate": 11025,
            "mod_path": "/home/michael/.local/share/Steam/ubuntu12_32/steamapps/common/Counter-Strike Source/css",
            "name": "Counter-Strike: Source",
            "play_key": "F8",
            "relay_key": "=",
            "use_aliases": true
        },
        {
            "audio_dir": "/run/media/michael/General/MusicSpam",
            "audio_rate": 11025,
            "mod_path": "/run/media/michael/General/steamapps/common/Team Fortress 2/tf",
            "name": "Team Fortress 2",
            "play_key": "F8",
            "relay_key": "=",
            "use_aliases": true
        }
    ],
    "steam_path": "/home/michael/.local/share/Steam/ubuntu12_32"
}
```

**Comment by 10se1ucgo** [comment]
Thanks.

Can you confirm that the path `/home/michael/.local/share/Steam/ubuntu12_32/userdata` exists? It seems that the file system watchdog cannot find that path.

**Comment by lolmikes** [comment]
It does not exist. Should I create one?

**Comment by lolmikes** [comment]
I created it and it runs without giving an error now. Now to figure out how to even play anything and that jam_help doesn't even work!!!!!

**Comment by 10se1ucgo** [comment]
The problem is that pyjam sets up event handlers for file write events on your Steam userdata folder (where game config files are saved) so that it can detect which song you have loaded, so creating an empty userdata folder will do nothing.

I think the problem is that the config detected the wrong folder for your Steam install (it's detecting where the Steam executable is located, which seems to be separated by folders on Linux). If I'm right, the proper path should probably be `/home/michael/.local/share/Steam/userdata/` OR `/home/michael/.steam/steam/userdata/`. Check if either of these paths exist.

**Comment by lolmikes** [comment]
Okay that's where the folder is and the .steam just links to the .local folder.  The only folder in userdata is one named "119277230" with many sub folders. jam_help still does nothing and all that hitting the play audio key does is play the sound from my microphone.

**Comment by 10se1ucgo** [comment]
Ah, okay.

Now, go into the config editor and make your Steam path `/home/michael/.local/share/Steam/`, and restart pyjam. It should start working.

Also, I don't think jam_help exists on your version of pyjam. It only exists on v1.3+, but I haven't created builds for them.

**Comment by lolmikes** [comment]
oh well umm.The path is correct and everything. I can see the track list in the console and it'll say I loaded one, but only plays my microphone still.

**Comment by 10se1ucgo** [comment]
`sv_use_steam_voice` needs to be `0` on the server.

**Comment by lolmikes** [comment]
okay it might be working. i can only hear my microphone in a server with that set to 1. The server i'm on right now has it set to 0 and it just doesn't play anything!

**Comment by 10se1ucgo** [comment]
Can you walk me through how you try to play a song?

**Comment by lolmikes** [comment]
okay umm. I open pyjam, hit start then run tf2 and type exec jam.cfg and nicocore" which then says it loaded and then finally hitting the play audio key. i hit the relay key too sometimes.

pyjam v1.2.9 loaded. Type  la  or  jam_listaudio  for a list of tracks. 
] la
0. rip again dumbass. Aliases: ['rip', 'again', 'dumbass'] 
1. NICOCORE. Aliases: ['nicocore'] 
] nicocore
Loaded : NICOCORE 
Host_WriteConfiguration: Wrote cfg/jam_cmd.cfg
Wrote partial config file "jam_cmd" out, to write full file use host_writeconfig "jam_cmd" full

**Comment by 10se1ucgo** [comment]
Okay,  can you attach the latest copy of `pyjam.log`? Just want to check if songs are being loaded by pyjam.

**Comment by lolmikes** [comment]
There's lots more stuff in it now. 
[pyjam.log.txt](https://github.com/10se1ucgo/pyjam/files/511196/pyjam.log.txt)

**Comment by 10se1ucgo** [comment]
Hmm. The problem seems to be that it can't find jam_cmd.cfg. On Windows, this is normally in the Steam userdata folder. However, it's possible that config files are still written to the game cfg directory.

Can you start pyjam, load a song, and check if jam_cmd.cfg exists in `/run/media/michael/General/steamapps/common/Team Fortress 2/tf/cfg`?

Sorry, I wish I had access to a Linux machine capable of running games :P

**Comment by lolmikes** [comment]
Yes jam_cmd exists in the /tf/cfg folder. and sorry i didn't check my email yesterday.

voice_input.wav certainly will never exist in that path 

09:09:58 ERROR: Could not remove some files:
Traceback (most recent call last):
  File "jam_tools.py", line 255, in stop
FileNotFoundError: [Errno 2] No such file or directory: '/run/media/michael/General/steamapps/common/Team Fortress 2/voice_input.wav'

**Comment by 10se1ucgo** [comment]
Alright, I know the problem then.

I'll start working on it in a bit.

**Comment by lolmikes** [comment]
Thank you for your help and your work!

**Comment by augustusthebear** [comment]
Hi, I know this is quite a ways in the past for you, but I am having the same issue and wondering if you figured anything out to fix this. The console says voice_fadeouttime is not a command it recognizes. Also, is .mp3 a fine format for the audio files?

additionally, everything launches fine and exec works well. I have followed the plot in this thread and made sure everything is right in jamconfig.json for csgo. but la in the console doesn't list any songs and the initial launch throws the voice fadeout error

**Comment by lolmikes** [comment]
No sorry, I was never able to figure it out and gave up. I'd try again now, but I can't afford a new GPU to play tf2

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
